config/routes.rb
Rails.application.routes.draw do
  resources :asteroids
  resources :calcs
  resources :asteroids
end

app/models/asteroid.rb
class Asteroid < ActiveRecord::Base
  has_many :mpcs
  has_many :calcs
end

app/models/calc.rb
class Calc < ActiveRecord::Base
  belongs_to :asteroid
end

app/models/mpc.rb
class Mpc < ActiveRecord::Base
  self.table_name = 'properties'

  belongs_to :asteroid

  M_INCLINATION = 1.85
  M_MIDR        = 227_900_000
  GM            = 132_700_000_000
  MASS_EQUIP    = 100 # in kg
  VE            = 50  #	exhaust velocity, about 3km/s for hydrogen+oxygen.
                      # 50 for ion plasma thruster
  VELAUNCH      = 5   #	exhaust velocity for launch, 5km/s
  AU            = 149_598_000 # AU in km

  # Calculator for delta-v and fuel
  def self.calc_mass_fuel_total(a_mass)

    calc = []

    # step 1 - Delta V from Asteroid to Mars
    Mpc.where('perihelion_distance > 1 AND aphelion_distance < 2').each do |mpc|

      a_inclination = mpc.inclination
      a_midr = mpc.semimajor_axis * AU
      deltaVneeded = mpc.delta_v

      # vis-viva equation, assuming blast at perogee
      velocity1 = Math::sqrt(GM / a_midr) # assumes blast is at the semi-major axis (midr)

      # delta-v for inclination change
      deltaV1a = Math::sqrt(2 * velocity1 * velocity1 * (1 - Math::cos(M_INCLINATION - a_inclination)))

      # delta-v for hohmann transfer
      deltaV1b = Math::sqrt(GM / a_midr) * (Math::sqrt(2 * a_midr / (a_midr + M_MIDR)) - 1).abs

      # step 2 - Fuel needed for DeltaV - uses deltaV from asteroid to Mars (above) and mass of the asteroid
      # mass is based on density (1.38 g/cm^3) * 4 π / 3 * radius^3 * (10000 cm/m * 10000 cm/m * 10000 cm/m) * (1 kg / 1000 g)
      # !! USER INPUT
      #a_mass = 5_000 # 1.38 * 4 / 3 * PI * (a_diameter * a_diameter * a_diameter) / 8 * 10E9

      fuelMass1 = (MASS_EQUIP + a_mass) * (Math::exp((deltaV1a + deltaV1b) / VE) - 1)

      # step 3 - Fuel needed to get to the Asteroid
      fuelMass2 = (MASS_EQUIP + fuelMass1) * (Math::exp(deltaVneeded / VE) - 1)

      # step 4 - Fuel needed to launch into LEO
      # deltaVtoLEO = 9 # km/s
      # fuelMass3 = (MASS_EQUIP + fuelMass1 + fuelMass2) * (Math::exp(deltaVtoLEO / VELAUNCH) - 1)
      fuelMassTotal = fuelMass1 + fuelMass2 # + fuelMass3

      calc << { name: mpc.n_or_d,
                designation: mpc.designation,
                diameter: mpc.diameter,
                mass_fuel_total: fuelMassTotal.to_f.round(2) }
    end

    calc.sort_by { |hsh| hsh[:mass_fuel_total] }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/asteroids_controller.rb
class AsteroidsController < ApplicationController
  before_action :set_asteroid, only: [:show, :edit, :update, :destroy]

  attr_accessor :mass

  # GET /asteroids
  def index
    @asteroids = Asteroid.all
    @asteroid  = Asteroid.new
  end

  # GET /asteroids/1
  def show
    @asteroids = Mpc.calc_mass_fuel_total(@asteroid.mass).slice(0,10)
  end

  # GET /asteroids/new
  def new
    @asteroid = Asteroid.new
  end

  # GET /asteroids/1/edit
  def edit
  end

  # POST /asteroids
  def create
    @asteroid = Asteroid.new(asteroid_params)

    if @asteroid.save
      redirect_to @asteroid
    else
      render :new
    end
  end

  # PATCH/PUT /asteroids/1
  def update
    if @asteroid.update(asteroid_params)
      redirect_to @asteroid
    else
      render :edit
    end
  end

  # DELETE /asteroids/1
  def destroy
    @asteroid.destroy
    redirect_to asteroids_url, notice: 'Asteroid was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asteroid
      @asteroid = Asteroid.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def asteroid_params
      params.require(:asteroid).permit(:mass)
    end
end

app/controllers/calc_controller.rb
class CalcController < ApplicationController
end

app/controllers/calcs_controller.rb
class CalcsController < ApplicationController
  before_action :set_calc, only: [:show, :edit, :update, :destroy]

  # GET /calcs
  def index
    @asteroid = Asteroid.new
  end

  # GET /calcs/1
  def show
  end

  # GET /calcs/new
  def new
    @calc = Calc.new
  end

  # GET /calcs/1/edit
  def edit
  end

  # POST /calcs
  def create
    @calc = Calc.new(calc_params)

    if @calc.save
      redirect_to @calc, notice: 'Calc was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /calcs/1
  def update
    if @calc.update(calc_params)
      redirect_to @calc, notice: 'Calc was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /calcs/1
  def destroy
    @calc.destroy
    redirect_to calcs_url, notice: 'Calc was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calc
      @calc = Calc.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def calc_params
      params[:calc]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/asteroids/_form.html.erb
<%= simple_form_for(@asteroid) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/asteroids/edit.html.erb
<h1>Editing Asteroid</h1>

<%= render 'form' %>

<%= link_to 'Show', @asteroid %> |
<%= link_to 'Back', asteroids_path %>

app/views/asteroids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asteroid Calculator</h1>

<%= simple_form_for @asteroid do |f| %>
  <%= f.input :mass %>
  <%= f.button :submit, value: "Find asteroids" %>
<% end %>

app/views/asteroids/new.html.erb
<h1>New Asteroid</h1>

<%= render 'form' %>

<%= link_to 'Back', asteroids_path %>

app/views/asteroids/show.html.erb
<%= simple_form_for @asteroid do |f| %>
  <%= f.input :mass, label: "Asteroid payload (kg)" %>
  <%= f.button :submit, value: "Find asteroids" %>
<% end %>

<hr style="border-bottom: 20px solid #000;">

<table class="table table-striped">
  <thead>
    <tr>
      <td>#</td>
      <td>name</td>
      <td>designation</td>
      <td>diameter</td>
      <td>fuel needed (kg)</td>
    </tr>
  </thead>
  <tbody>
    <% @asteroids.each_with_index do |a,i| %>
      <tr>
        <td><%= i + 1 %></td>
        <td><%= a[:name] %></td>
        <td><%= a[:designation] %></td>
        <td><%= a[:diameter] %></td>
        <td><%= a[:mass_fuel_total] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', asteroids_path %>

app/views/calcs/_form.html.erb
<%= simple_form_for(@calc) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/calcs/edit.html.erb
<h1>Editing Calc</h1>

<%= render 'form' %>

<%= link_to 'Show', @calc %> |
<%= link_to 'Back', calcs_path %>

app/views/calcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asteroid Calculator</h1>

app/views/calcs/new.html.erb
<h1>New Calc</h1>

<%= render 'form' %>

<%= link_to 'Back', calcs_path %>

app/views/calcs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_calc_path(@calc) %> |
<%= link_to 'Back', calcs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>